PK
FK
UNIQUE
INDEX

@startuml database

class OAUTH_CLIENT_DETAILS <<(T,#DDDDDD)>> {
    客户端信息
    ==
    CLIENT_ID : VARCHAR(256) PK NOT NULL -- 客户端ID
    RESOURCE_IDS : VARCHAR(256) NULL -- 资源ID
    CLIENT_SECRET : INTEGER(10) DEFAULT 0 NULL -- 客户端密码
    SCOPE : VARCHAR(256) DEFAULT 'a' NULL -- 授权范围
    AUTHORIZED_GRANT_TYPES : VARCHAR(256) NULL -- 授权方式
    WEB_SERVER_REDIRECT_URI : VARCHAR(256) NULL -- 服务器跳转地址
    AUTHORITIES : VARCHAR(256) NULL -- 权限
    ACCESS_TOKEN_VALIDITY : INTEGER(10) NULL -- 授权TOKEN有效时间
    REFRESH_TOKEN_VALIDITY : INTEGER(10) NULL -- 刷新TOKEN有效时间
    ADDITIONAL_INFORMATION : VARCHAR(4096) NULL -- 附加信息
    AUTOAPPROVE : VARCHAR(256) NULL -- 是否自动批准
}

class OAUTH_CLIENT_TOKEN <<(T,#DDDDDD)>> {
    客户端TOKEN
    ==
    TOKEN_ID : VARCHAR(256) UNIQUE NULL -- TOKEN ID
    TOKEN : VARBINARY(2147483647) NULL -- TOKEN
    AUTHENTICATION_ID : VARCHAR(256) PK NOT NULL -- 权限信息ID
    USER_NAME : VARCHAR(256) NULL -- 用户名
    CLIENT_ID : VARCHAR(256) INDEX NULL -- 客户端ID
    'INDEX USER_NAME,TOKEN
}

@enduml