-- USED IN TESTS THAT USE HSQL
CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(256) PRIMARY KEY ,
  RESOURCE_IDS VARCHAR(256) ,
  CLIENT_SECRET INTEGER(11) default 0,
  SCOPE VARCHAR(256) DEFAULT 'a',
  AUTHORIZED_GRANT_TYPES VARCHAR(256) ,
  WEB_SERVER_REDIRECT_URI VARCHAR(256) ,
  AUTHORITIES VARCHAR(256) ,
  ACCESS_TOKEN_VALIDITY INTEGER ,
  REFRESH_TOKEN_VALIDITY INTEGER ,
  ADDITIONAL_INFORMATION VARCHAR(4096) ,
  AUTOAPPROVE VARCHAR(256)
);
COMMENT ON TABLE OAUTH_CLIENT_DETAILS IS '客户端信息';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_ID IS '客户端ID';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.RESOURCE_IDS IS '资源ID';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_SECRET IS '客户端密码';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.SCOPE IS '授权范围';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORIZED_GRANT_TYPES IS '授权方式';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.WEB_SERVER_REDIRECT_URI IS '服务器跳转地址';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORITIES IS '权限';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.ACCESS_TOKEN_VALIDITY IS '授权TOKEN有效时间';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.REFRESH_TOKEN_VALIDITY IS '刷新TOKEN有效时间';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.ADDITIONAL_INFORMATION IS '附加信息';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.AUTOAPPROVE IS '是否自动批准';

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(256) unique ,
  TOKEN LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME VARCHAR(256),
  CLIENT_ID VARCHAR(256)
);

COMMENT ON TABLE OAUTH_CLIENT_TOKEN IS '客户端TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN_ID IS 'TOKEN ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN IS 'TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID IS '权限信息ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.USER_NAME IS '用户名';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.CLIENT_ID IS '客户端ID';
CREATE INDEX IDXNAME ON OAUTH_CLIENT_TOKEN(USER_NAME,TOKEN);

ALTER TABLE OAUTH_CLIENT_TOKEN ADD FOREIGN KEY ( CLIENT_ID ) REFERENCES OAUTH_CLIENT_DETAILS( CLIENT_ID ) ;