PK
FK
UNIQUE
INDEX

@startuml 基础

class NHR_DICS <<(T,#DDDDD3)>> {
    数据字典
    ==
    DIC_ID : NUMBER(20) PK -- 主键ID
    DIC_CODE : VARCHAR2(50) NULL UNIQUE -- 字典编码
    DIC_NAME : VARCHAR2(50) NULL -- 字典名
}

class NHR_DICITEM <<(T,#DDDDD4)>> {
    数据字典条目
    ==
    DIC_ITEM_ID : NUMBER(20) PK -- 主键ID
    DIC_CODE : VARCHAR2(50) FK > NHR_DICS.DIC_CODE NULL -- 字典编码
    DIC_ITEM_CODE : VARCHAR2(50) NULL -- 子项编码
    DIC_ITEM_NAME : VARCHAR2(100) NULL -- 子项名
    SEQ : NUMBER(4,0) DEFAULT 0 NULL -- 顺序
    'UNIQUE DIC_CODE,DIC_ITEM_CODE
}

NHR_DICS "1" -- "0..*" NHR_DICITEM

class NHR_SYS_SETTING <<(T,#DDDDDD)>> {
    系统配置
    ==
    SETTING_ID : NUMBER(20) PK -- 配置主键ID
    SETTING_TYPE : VARCHAR2(64) NULL -- 配置类型
    SETTING_KEY : VARCHAR2(200) NULL -- 键
    SETTING_VALUE : VARCHAR2(200) NULL -- 值
    SETTING_DESC : VARCHAR2(200) NULL -- 说明备注
    IS_DEL :  NUMBER(1) DEFAULT 0 NOT NULL -- 是否删除（1：标记删除；0：正常）
}

@enduml
