summer:
  logging:
    spilt-marker:
      request: info
    spilt-level:
      - error
      - warn
    request:
      include-path: /oauth/*
      include-request-body: true
      include-response-body: true
    slack:
      ignored-warn-logger:
        - org.springframework.security.oauth2.provider.endpoint.TokenEndpoint


spring:
  security:
    filter:
      dispatcher-types: REQUEST
  mvc:
    dispatchOptionsRequest: true
  messages:
    cache-duration: PT10S
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_BIGDECIMAL_AS_PLAIN: true
      WRITE_ENUMS_USING_INDEX: true
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: Asia/Shanghai
    locale: zh_CN

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    open-in-view: true
    show-sql: true
  datasource:
    hikari:
      connection-timeout: 60000

security:
  oauth2:
    client:
      scope: trust
      auto-approve-scopes: true
      authorized-grant-types: password,refresh_token

mybatis:
  configuration:
    map-underscore-to-camel-case: true


server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: PT10M
    encoding:
      force: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true


logging:
  level:
    org.springframework.boot.web.servlet.support.ErrorPageFilter: off
    org.mybatis.spring.mapper.ClassPathMapperScanner: error
    org.springframework.data.convert.CustomConversions: error
    org.springframework.boot.context.logging.ClasspathLoggingApplicationListener: warn
    org.springframework.boot.SpringApplication: warn
    org.springframework.context.annotation.AnnotationConfigApplicationContext: warn
    org.springframework.core.env.PropertySourcesPropertyResolver: warn
    org.springframework.beans.factory.support.DefaultListableBeanFactory: warn
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: warn
    com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter: warn
    com.ulisesbocchio.jasyptspringboot.filter.DefaultLazyPropertyFilter: warn
    com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor: warn
    reactor.util.Loggers: info
    org.jboss: warn
    io.micrometer: warn
    org.springframework: warn
    org.springframework.cloud: warn
    jdk.event.security: warn
    _org.springframework: warn
    org.springframework.boot.availability: warn
    org.springframework.boot.actuate: warn
    org.springframework.web.servlet: warn
    com.ulisesbocchio: warn
    io.lettuce: warn
    org.thymeleaf: warn
    javax.management: warn
    org.quartz: warn
    io.netty: warn
    com.alibaba: warn
    com.zaxxer.hikari: warn
    springfox: warn
    com.baomidou: warn
    org.apache: warn
    org.hibernate: warn
    org.mybatis: warn
    com.netflix: warn
    com.sun: warn
    javax.xml: warn
    net.sf: warn
    javax.activation: warn
    org.mongodb: warn
    top.bettercode: info
