CREATE TABLE if not exists OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(256) unique ,
  TOKEN LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME VARCHAR(256),
  CLIENT_ID INTEGER(10)
);

COMMENT ON TABLE OAUTH_CLIENT_TOKEN IS '客户端TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN_ID IS 'TOKEN ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN IS 'TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID IS '权限信息ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.USER_NAME IS '用户名';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.CLIENT_ID IS '客户端ID';